server:
  port: 8026
spring:
  datasource:
    url: jdbc:mysql://192.168.111.3:3306/wallet1.1-server?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: wallet1.1-server
    password: wallet1.1-server
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 20
      min-idle: 3
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: select 'x'
      validation-query-timeout: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 50000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      filters: stat,wall
      web-stat-filter:
        enabled: false
        principal-cookie-name: USER_COOKIE
        principal-session-name: USER_SESSION
        session-stat-enable: false
        url-pattern: /*
        exclusions: .js,.css,.png,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: (*()KJKmdindudruid#2*#%$#@$jdhs
        allow: 192.168.170.1,127.0.0.1
        deny: 192.168.1.136
      filter:
        log4j:
          enabled: false
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

sa-token:
  is-read-cookie: true # 是否从 Cookie 读取 Token
  is-read-header: true # 是否从 Header 读取 Token
  is-read-body: true   # 是否从 Body 读取 Token
  ############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
  # token 名称（同时也是 cookie 名称）
  token-name: X-Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  # 配置Sa-Token使用内存存储而不是Redis存储
  storage-type: memory

