server:
  port: 8026
spring:
  datasource:
    url: jdbc:mysql://qdserver:3306/smart_task?characterEncoding=utf8&connectTimeout=15000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: smart_task
    password: smart_task
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 2
      max-active: 20
      min-idle: 3
      max-wait: 120000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      max-open-prepared-statements: 20
      validation-query: select 'x'
      validation-query-timeout: 20
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 50000
      min-evictable-idle-time-millis: 30000
      max-evictable-idle-time-millis: 60000
      filters: stat,wall
      web-stat-filter:
        enabled: false
        principal-cookie-name: USER_COOKIE
        principal-session-name: USER_SESSION
        session-stat-enable: false
        url-pattern: /*
        exclusions: .js,.css,.png,/druid/*
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: (*()KJKmdindudruid#2*#%$#@$jdhs
        allow: 192.168.170.1,127.0.0.1
        deny: 192.168.1.136
      filter:
        log4j:
          enabled: false
  redis:
    host: 192.168.111.223
    port: 65001
    password: "*OUojasofu203rjoajsdlfsu2381232434313122334132dsgdzgGDW38*"
    timeout: 10000s
    jedis:
      pool:
        max-idle: 20
        min-idle: 5
        max-active: 20
        max-wait: 10000s

#  messages:
#    basename: /Volumes/Data/source/java/my/wallet3.0/target/classes/messages/messages
#    encoding: UTF-8
logging:
  level:
    root: info
    org.mybatis: info
    top.itoken.wallet3: info

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: com.lvpai.equipm.entity;com.lvpai.equipm.entity.*
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    db-config:
      id-type: AUTO
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      table-underline: true
      #数据库大写下划线
      #capital-mode: true
      # Sequence序列接口实现类配置
      #逻辑删除配置（下面3个配置）
      logic-delete-value: 1
      logic-not-delete-value: 0
        #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
        #自定义填充策略接口实现
      #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    plugins:
      - com.baomidou.mybatisplus.extension.plugins.MybatisPlusInterceptor
    map-underscore-to-camel-case: true
    cache-enabled: true
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#logging:
  level:
    root: debug
    io.lettuce.core: DEBUG
#    org:
#      springframework:
#        context:
#          support: DEBUG
#    org.springframework.context.support: DEBUG

  file:
    path: ./logs/
    name: log


sa-token:
  is-read-cookie: true # 是否从 Cookie 读取 Token
  is-read-header: true # 是否从 Header 读取 Token
  is-read-body: true   # 是否从 Body 读取 Token
  ############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
  # token 名称（同时也是 cookie 名称）
  token-name: X-Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  data-storage:
    type: file           # 配置为文件模式
    path: ./session/ # 文件存储路径

